export const DefaultThemes = {
  widthSite: {
    XXXSmallMobileFontSize: '9px',
    widthLoginPage: '32.250em',
  },
  heightSite: {
    heightTopNavBar: '4.5em',
  },
  paddingSite: {
    XXXSmallMobileFontSize: '9px',
  },
  boxShandow: {
    loginPage: '0px 0px 17px -3px #2a3a516e',
  },
  fontSize: {
    XXXSmallMobileFontSize: '9px',
    XXSmallMobileFontSize: '10px',
    XSmallMobileFontSize: '0.525em',
    SmallMobileFontSize: '0.625em',
    DefaultFonts: '0.688em',
    SmallFontSize: '0.750em',
    MediumFontSize: '0.875em',
    BaseFontSize: '1em',
    HeadingH6FontSize: '1.125em',
    HeadingH5FontSize: '1.225em',
    HeadingH4FontSize: '1.325em',
    HeadingH3FontSize: '1.425em',
    HeadingH2FontSize: '1.5em',
    HeadingH1FontSize: '1.6em',
    XLargeFontSize: '1.9em',
    LargeFontSize: '24px',
    XXXLargeFontSize: '42px',
  },
  borderRadius: {
    borderbtn: '0.6em',
    borderBlock: '0.6em',
    borderBtnSmall: '0.3em',
  },
  colorStyled: {
    ColorWhite: '#ffffff',
    ColorBlack: '#000000',
    ColorBgDefault: '#ff5402',
    ColorTransparent: 'transparent',
    ColorBgDefaultHover: '#d67f04',
    ColorBgUser: '#ff5502',
    ColorPrimary: '#ff5402',
    ColorSecond: '#586069',
    ColorGrey: '#dfdfdf',
    ColorDarkGrey: '#6e6c83',
    ColorMidGrey: '#4a4a4a',
    ColoraBtnPrimary: '#2697ea',
    ColoraBtnCancel: '#898c8e',
    ColorBorder: '#d9d9d9',
    ColorWarming: '#b52d2d',
    ColorIcon: '#eb9388',
    ColorIconHover: '#d50000',
    ColorBtnFb: '#3b5998',
    iconAddColor: '#2fa3e6',
    iconAddHoverColor: '#036299',
    iconMoreColor: '#227fb5',
    iconMoreHoverColor: '#0f496b',
    ColorXLightGrey: '#2f2f2f',
    ColorXXLightGrey: '#6e6c83fa',
    ColorXXXLightGrey: '#eee',


    ColorBgSilver: '#f8f9fa',
    ColorBgHover: '#ffe2ba',
    ColorBgContent: '#f6f7fb',
    ColorDark: '#1b1b1b',
    ColorYellowCheckbox: '#ffc700',
    ColorRedDel: '#d72111',
    colorLightGrey: '#bdb8b6',
    colorBtn: '#ffe2c0',
    colorBorder: '#e7e7e7',

    ColorPrimaryGreen: '#1bd18a',
    ColorPrimaryBlue: '#4886ff',
    ColorBgMyCourses: '#fbfbfb',
    ColorBgSideBarDefault: '#f3f6f8',
    ColorDefault: '#6f6f6f',
    ColorSuccess: '#1bd18a',
    ColorSuccessN: '#4cbe2d',
    ColorTime: '#a3adba',

    ColorXBorder: '#e0dedb',
    ColorPoint: '#a5a5a5',
    ColorBorderClassNav: '#edeff1',
    ColorLink: '#433aef',
    ColorActiveCheckbox: '#18c798',
    ColorLevelKill: '#8c9093',
    ColorLevelKillActive: '#1787e2',
    ColorBgClassNav: '#f7f9fa',
    ColorBoxShandow: '#e5e5e67a',
    ColorSilver: '#a4a4a4',
    ColorBgForm: '#ececec',
    ColorSkipped: '#bdbdbd',
    ColorMing: '#385e7e',
    ColorPeach: '#fee2b4',
    ColorBgAvartar: '#d2d2d2',
    ColorUser: '#1a1a1a',
    ColorWarning: '#ed1c24',

    ColorBorderSilver: '#cbcbcb',
    ColorBorderPractice: '#dedede',
    ColorBorderHampton: '#e3d0ad',
    ColorTimeZoneItemWhite: 'white',
    ColorSilverChalice: '#9e9e9e',
    ColorBgSeashell: '#f1f1f1',
    ColorAlto: '#d6d6d6',
    ColorAlizarinCrimson: '#D92222',
    ColorFunGreen: '#01a41c',
    ColorDoveGray: '#6e6e6e',

    ColorGreenPoint: '#34DF9D',
    ColorRedPoint: '#ba0c28',
    ColorSelectedScoreSeperate: 'rgba(163,173,186,0.2)',
    ColorSectionDashboard: '#767C84',
    ColorTopicUpIcon: '#415063',
    ColorTableHeader: '#0c0d12',
    ColorScoreStep: '#0f1013',
    ColorLightCoral: '#ff7f7f',
    ColorOrange: '#ff9e16',
    ColorRedGray: '#453635',
  },
};
